package router

import (
	kb "interview-agents/api/handler/kb"
	"interview-agents/internal/config"
	"interview-agents/internal/rag/phase3"
	"log"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/route"
)

func registerKnowledgeBaseRoutes(r *server.Hertz) {
	if !config.Global.RAG.Enabled {
		log.Println("[RAG] RAG is disabled, skipping knowledge base routes registration")
		return
	}
	log.Println("[RAG] Registering knowledge base routes")
	registerKBGroup(r.Group("/api/kb"), false)
	registerKBGroup(r.Group("/api/admin/kb"), true)
}

func registerKBGroup(group *route.RouterGroup, adminOnly bool) {
	group.GET("/dashboard/stats", kb.GetDashboardStats)
	group.POST("/bases", kb.CreateKnowledgeBase)
	group.GET("/bases", kb.ListKnowledgeBases)
	group.DELETE("/bases/:kb_id", kb.DeleteKnowledgeBase)
	group.POST("/documents/upload", kb.UploadDocument)
	group.GET("/documents", kb.ListDocuments)
	group.GET("/jobs", kb.ListJobs)
	group.GET("/jobs/:job_id", kb.GetJob)
	group.POST("/jobs/:job_id/retry", kb.RetryJob)
	group.POST("/jobs/:job_id/cancel", kb.CancelJob)
	group.DELETE("/documents/:document_id", kb.DeleteDocument)
	group.POST("/retrieve", kb.Retrieve)
	group.GET("/retrieve/audit/:request_id", kb.GetRetrieveAuditLog)
	group.GET(phase3.LegacyRetrievalDebugRoute, kb.GetRetrieveDebugView)
	group.GET(phase3.RetrievalDebugRoute, kb.GetRetrieveDebugView)
	group.GET("/retrieve/audit", kb.ListRetrieveAuditLogs)
	group.GET("/metrics/overview", kb.GetMetricsOverview)
	group.GET("/logs/ingest", kb.ListIngestLogs)
	group.GET("/logs/ingest/:job_id", kb.GetIngestLogDetail)
	group.POST("/ingest/pause", kb.PauseIngest)
	group.POST("/ingest/resume", kb.ResumeIngest)
	group.GET("/ingest/status", kb.GetIngestStatus)
	if adminOnly {
		group.GET("/eval/datasets", kb.ListEvalDatasets)
		group.POST("/eval/datasets", kb.CreateEvalDataset)
		group.GET("/eval/datasets/:dataset_id/items", kb.ListEvalCases)
		group.POST("/eval/datasets/:dataset_id/items", kb.CreateEvalCase)
		group.POST("/eval/datasets/:dataset_id/items/import", kb.ImportEvalCases)
		group.GET("/eval/datasets/:dataset_id/items/export", kb.ExportEvalCases)
		group.POST("/eval/datasets/:dataset_id/validate", kb.ValidateEvalDataset)
		group.GET("/eval/runs", kb.ListEvalRuns)
		group.POST("/eval/runs", kb.CreateEvalRun)
		group.GET("/eval/runs/:run_id", kb.GetEvalRun)
		group.GET("/eval/runs/:run_id/report", kb.GetEvalReport)
		group.GET("/eval/runs/:run_id/cases", kb.ListEvalFailureCases)
		group.GET("/eval/runs/:run_id/report/export", kb.ExportEvalReport)
		group.GET("/strategy/flags", kb.ListStrategyFlags)
		group.PATCH("/strategy/flags/:flag_key", kb.UpdateStrategyFlag)
		group.GET("/strategy/versions", kb.ListStrategyVersions)
		group.GET("/strategy/versions/:version_id", kb.GetStrategyVersion)
		group.POST("/strategy/rollback", kb.RollbackStrategy)
		group.GET("/strategy/impact", kb.GetStrategyImpact)
		group.GET("/strategy/gates", kb.GetStrategyGates)
		group.GET("/strategy/operations", kb.ListStrategyOperations)
		group.GET("/experiments", kb.ListExperiments)
		group.POST("/experiments", kb.SaveExperiment)
		group.POST("/experiments/:experiment_id/rollback", kb.RollbackExperiment)
		group.GET("/experiments/summary", kb.GetExperimentSummaries)
		group.GET("/index-lifecycle/registry", kb.ListIndexRegistry)
		group.POST("/index-lifecycle/register", kb.RegisterIndexFromConfig)
		group.POST("/index-lifecycle/build", kb.BuildCandidateIndex)
		group.GET("/index-lifecycle/health/:index_version", kb.GetIndexHealth)
		group.POST("/index-lifecycle/switch/:index_version", kb.SwitchActiveIndex)
		group.POST("/index-lifecycle/rollback", kb.RollbackActiveIndex)
		group.GET("/index-lifecycle/operations", kb.ListIndexOperations)
		group.GET("/cost/summary", kb.GetCostSummary)
		group.GET("/cost/timeseries", kb.GetCostTimeseries)
		group.GET("/cost/by-kb", kb.GetCostByKB)
		group.GET("/cost/by-strategy", kb.GetCostByStrategy)
		group.GET("/cost/by-model", kb.GetCostByModel)
		group.GET("/cost/high-cost-queries", kb.ListHighCostQueries)
		group.GET("/vector/collections", kb.ListVectorCollections)
		group.GET("/vector/collections/:name/health", kb.GetVectorCollectionHealth)
		group.GET("/vector/collections/:name/capacity", kb.GetVectorCollectionCapacity)
		group.POST("/vector/collections/:name/rebuild", kb.RebuildVectorCollection)
		group.POST("/vector/collections/:name/switch", kb.SwitchVectorCollection)
		group.POST("/vector/collections/:name/rollback", kb.RollbackVectorCollection)
		group.GET("/vector/operations", kb.ListVectorOperations)
		group.GET("/audit/events", kb.ListAuditEvents)
		group.GET("/audit/events/:event_id", kb.GetAuditEventDetail)
		group.POST("/audit/events/export", kb.ExportAuditEvents)
		group.GET("/alerts", kb.ListAlerts)
		group.PATCH("/alerts/:alert_id/ack", kb.AckAlert)
		group.PATCH("/alerts/:alert_id/resolve", kb.ResolveAlert)
		group.POST("/reports/weekly", kb.CreateWeeklyReport)
		group.GET("/reports/weekly", kb.ListWeeklyReports)
		group.GET("/reports/weekly/:report_id", kb.GetWeeklyReportDetail)
		group.POST("/reports/weekly/:report_id/export", kb.ExportWeeklyReport)
		group.GET("/weekly-report", kb.GetWeeklyReport)
		group.GET("/governance/gates", kb.GetGovernanceGate)
		group.POST("/governance/gates/check", kb.CheckGovernanceGates)
		group.GET("/governance/gate", kb.GetGovernanceGate)
		group.GET("/phase4/acceptance", kb.GetPhase4Acceptance)
		group.GET("/release/status", kb.GetReleaseStatus)
		group.GET("/release/summary", kb.GetReleaseSummary)
		group.POST("/release/rollback", kb.RollbackRelease)
		group.POST("/release/activate", kb.ActivateRelease)
	}
}
