// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	interview "interview-agents/api/router/interview"
	paymentRouter "interview-agents/api/router/payment"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	interview.Register(r)
	paymentRouter.Register(r)
}
