// Code generated by hertz generator.

package resume

import (
	"context"
	"fmt"
	interviewsapi "interview-agents/api/model/resume"
	"interview-agents/api/response"
	"interview-agents/internal/middleware"
	"interview-agents/internal/model"
	"interview-agents/internal/mq"
	interviewservice "interview-agents/internal/service/resume"
	"interview-agents/internal/storage"
	"log"
	"mime/multipart"

	"os"
	"path/filepath"
	"time"

	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetInterviewRecords .
// @router /api/interview/records [GET]
func GetInterviewRecords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviewsapi.ListInterviewRecordsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	records, total, err := interviewservice.NewInterviewService().ListInterviewRecords(ctx, userID, req.Page, req.PageSize)
	if err != nil {
		response.ErrorFromErr(ctx, c, err)
		return
	}

	resp := new(interviewsapi.ListInterviewRecordsResponse)
	resp.Records = records
	resp.Total = total

	response.Success(ctx, c, resp)
}

// UploadResume 上传简历（异步处理）
// @router /api/resume/upload [POST]
func UploadResume(ctx context.Context, c *app.RequestContext) {
	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}
	// 处理文件上传
	resumeFilePath, err := handleResumeUpload(ctx, c)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}
	if resumeFilePath == "" {
		response.BadRequest(ctx, c, "No resume file uploaded")
		return
	}
	// 获取文件信息
	fileHeader, err := c.FormFile("resume")
	if err != nil {
		response.BadRequest(ctx, c, "Failed to get file info: "+err.Error())
		return
	}

	// 创建简历记录（状态为 pending）
	resumeRecord := &model.Resume{
		UserID:    userID,
		Status:    "pending",
		FilePath:  resumeFilePath,
		FileName:  fileHeader.Filename,
		FileSize:  fileHeader.Size,
		FileType:  "pdf",
		IsDefault: 1,
		Deleted:   0,
	}
	dbResumeID, err := model.ResumeDao.CreateResume(resumeRecord)
	if err != nil {
		log.Printf("[UploadResume] 创建简历记录失败: %v", err)
		response.ErrorFromErr(ctx, c, err)
		return
	}

	// 发布异步解析消息
	err = mq.PublishResumeParse(ctx, userID, dbResumeID, resumeFilePath, fileHeader.Size)
	if err != nil {
		log.Printf("[UploadResume] 发布解析消息失败: %v", err)
		// 即使消息发布失败，也返回成功，稍后可以重试
		// 更新状态为 failed
		_ = model.ResumeDao.UpdateResumeStatus(dbResumeID, "failed", "Failed to publish parse message: "+err.Error())
	}

	log.Printf("[UploadResume] 简历上传成功，异步解析中: resumeID=%d, userID=%d", dbResumeID, userID)

	// 立即返回，不等待解析完成
	statusPtr := "pending"
	resp := &interviewsapi.UploadResumeResponse{
		ResumeID: int64(dbResumeID),
		Message:  "Resume uploaded, parsing in progress",
		Status:   &statusPtr,
	}

	response.Success(ctx, c, resp)
}

// getOSS 获取 OSS 实例 (目前返回本地存储实现)
// TODO: 后期可以从配置文件读取配置，决定使用 LocalOSS 还是 MinIO
func getOSS() (storage.OSS, error) {
	basePath := filepath.Join(os.Getenv("PWD"), "uploads", "resumes")
	return storage.NewLocalOSS(basePath)
}

// handleResumeUpload 处理简历文件上传
func handleResumeUpload(ctx context.Context, c *app.RequestContext) (string, error) {
	fileHeader, err := c.FormFile("resume")
	if err != nil || fileHeader == nil {
		return "", nil // 没有上传文件不是错误
	}

	// 验证文件类型
	if filepath.Ext(fileHeader.Filename) != ".pdf" {
		return "", fmt.Errorf("只支持 PDF 格式的简历文件")
	}

	// 验证文件大小
	if fileHeader.Size > 10*1024*1024 {
		return "", fmt.Errorf("文件大小不能超过 10MB")
	}

	// 打开上传的文件
	file, err := fileHeader.Open()
	if err != nil {
		return "", fmt.Errorf("无法打开上传的文件: %v", err)
	}
	defer func(file multipart.File) {
		err := file.Close()
		if err != nil {
			log.Printf("[handleResumeUpload] warning: failed to close file: %v", err)
		}
	}(file)

	// 获取 OSS 实例
	ossClient, err := getOSS()
	if err != nil {
		return "", fmt.Errorf("系统存储初始化失败: %v", err)
	}

	// 生成唯一的文件名 (key)
	timestamp := time.Now().UnixNano()
	fileName := fmt.Sprintf("resume_%d_%s", timestamp, fileHeader.Filename)

	// 上传文件
	// 注意: c 是 RequestContext, 实现了 context.Context
	storedPath, err := ossClient.PutObject(ctx, fileName, file, fileHeader.Size, "application/pdf")
	if err != nil {
		return "", fmt.Errorf("文件保存失败: %v", err)
	}

	// 对于 LocalOSS，storedPath 就是绝对路径，可以直接用于后续的 PDF 解析
	// 如果将来切换到 MinIO，这里可能需要调整：
	// 1. 如果 PDF 解析器支持 URL，则使用 GetURL 获取
	// 2. 如果 PDF 解析器只支持本地路径，则需要先 Download 到临时文件
	return storedPath, nil
}

// GetResume 获取简历详情
// @router /api/resume/:resume_id [GET]
func GetResume(ctx context.Context, c *app.RequestContext) {
	var req interviewsapi.GetResumeRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}

	resumeService := interviewservice.NewResumeService()
	data, err := resumeService.GetResumeInfoByID(ctx, uint64(req.ResumeID))
	if err != nil {
		log.Printf("[GetResume] 获取简历失败: %v", err)
		response.InternalServerError(ctx, c, "Failed to get resume: "+err.Error())
		return
	}

	// 直接使用 map 响应
	resp := map[string]interface{}{
		"resume": data,
	}

	response.Success(ctx, c, resp)
}

// GetUserResumes 获取用户简历列表
// @router /api/resume/list [GET]
func GetUserResumes(ctx context.Context, c *app.RequestContext) {
	var req interviewsapi.GetUserResumesRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}

	page := int32(1)
	if req.Page != nil && *req.Page > 0 {
		page = *req.Page
	}

	pageSize := int32(10)
	if req.PageSize != nil && *req.PageSize > 0 {
		pageSize = *req.PageSize
	}

	resumeService := interviewservice.NewResumeService()
	data, total, err := resumeService.ListResumeInfosByUserID(ctx, userID, page, pageSize)
	if err != nil {
		log.Printf("[GetUserResumes] 获取简历列表失败: %v", err)
		response.InternalServerError(ctx, c, "Failed to get resumes: "+err.Error())
		return
	}

	// 直接使用 map 响应（因为服务层返回的是 []map[string]interface{}）
	resp := map[string]interface{}{
		"resumes":   data,
		"total":     total,
		"page":      page,
		"page_size": pageSize,
	}

	response.Success(ctx, c, resp)
}

// GetDefaultResume 获取默认简历
// @router /api/resume/default [GET]
func GetDefaultResume(ctx context.Context, c *app.RequestContext) {
	var req interviewsapi.GetDefaultResumeRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}

	resumeService := interviewservice.NewResumeService()
	data, err := resumeService.GetDefaultResumeInfo(ctx, userID)
	if err != nil {
		log.Printf("[GetDefaultResume] 获取默认简历失败: %v", err)
		response.InternalServerError(ctx, c, "Failed to get default resume: "+err.Error())
		return
	}

	// 直接使用 map 响应
	resp := map[string]interface{}{
		"resume": data,
	}

	response.Success(ctx, c, resp)
}

// SetDefaultResume 设置默认简历
// @router /api/resume/set-default [POST]
func SetDefaultResume(ctx context.Context, c *app.RequestContext) {
	var req interviewsapi.SetDefaultResumeRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}

	resumeService := interviewservice.NewResumeService()
	err = resumeService.SetDefaultResume(ctx, userID, uint64(req.ResumeID))
	if err != nil {
		log.Printf("[SetDefaultResume] 设置默认简历失败: %v", err)
		response.InternalServerError(ctx, c, "Failed to set default resume: "+err.Error())
		return
	}

	resp := &interviewsapi.SetDefaultResumeResponse{
		Message: "Default resume set successfully",
	}

	response.Success(ctx, c, resp)
}

// UpdateResume 更新简历
// @router /api/resume/:resume_id [PUT]
func UpdateResume(ctx context.Context, c *app.RequestContext) {
	var req interviewsapi.UpdateResumeRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}

	fileName := ""
	if req.FileName != nil {
		fileName = *req.FileName
	}

	resumeService := interviewservice.NewResumeService()
	err = resumeService.UpdateResume(ctx, uint64(req.ResumeID), fileName, "")
	if err != nil {
		log.Printf("[UpdateResume] 更新简历失败: %v", err)
		response.InternalServerError(ctx, c, "Failed to update resume: "+err.Error())
		return
	}

	resp := &interviewsapi.UpdateResumeResponse{
		Message: "Resume updated successfully",
	}

	response.Success(ctx, c, resp)
}

// DeleteResume 删除简历
// @router /api/resume/:resume_id [DELETE]
func DeleteResume(ctx context.Context, c *app.RequestContext) {
	var req interviewsapi.DeleteResumeRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}

	resumeService := interviewservice.NewResumeService()
	err = resumeService.DeleteResume(ctx, userID, uint64(req.ResumeID))
	if err != nil {
		log.Printf("[DeleteResume] 删除简历失败: %v", err)
		response.InternalServerError(ctx, c, "Failed to delete resume: "+err.Error())
		return
	}

	resp := &interviewsapi.DeleteResumeResponse{
		Message: "Resume deleted successfully",
	}

	response.Success(ctx, c, resp)
}
