// Code generated by hertz generator. DO NOT EDIT.

package interview

import (
	interview "interview-agents/api/handler/interview"
	resume "interview-agents/api/handler/resume"

	"github.com/cloudwego/hertz/pkg/app/server"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_interview := _api.Group("/interview", _interviewMw()...)
			_interview.GET("/records", append(_getinterviewrecordsMw(), resume.GetInterviewRecords)...)
		}
		{
			_interviewCore := _api.Group("/interview", _mianshiMw()...)
			_interviewCore.GET("/answer-record", append(_getmianshianswerrecordMw(), interview.GetInterviewAnswerRecord)...)
			_interviewCore.GET("/evaluation", append(_getmianshievaluationMw(), interview.GetInterviewEvaluation)...)
			{
				_answer := _interviewCore.Group("/answer", _answerMw()...)
				_answer.POST("/submit", append(_submitmianshianswerMw(), interview.SubmitInterviewAnswer)...)
			}
			{
				_interview0 := _interviewCore.Group("/interview", _interview0Mw()...)
				_interview0.POST("/end", append(_endmianshiMw(), interview.EndInterview)...)
			}
			{
				_session := _interviewCore.Group("/session", _sessionMw()...)
				_session.GET("/info", append(_getsessionMw(), interview.GetSession)...)
			}
			{
				_stream := _interviewCore.Group("/stream", _streamMw()...)
				_stream.POST("/start", append(_startmianshistreamMw(), interview.StartInterviewStream)...)
			}
		}
		{
			_prediction := _api.Group("/prediction", _predictionMw()...)
			_prediction.GET("/:id", append(_getpredictiondetailMw(), interview.GetPredictionDetail)...)
			_prediction.GET("/list", append(_listpredictionsMw(), interview.ListPredictions)...)
			_prediction.POST("/start", append(_predictMw(), interview.Predict)...)
		}
		{
			_resume := _api.Group("/resume", _resumeMw()...)
			_resume.GET("/default", append(_getdefaultresumeMw(), resume.GetDefaultResume)...)
			_resume.GET("/list", append(_getuserresumesMw(), resume.GetUserResumes)...)
			_resume.DELETE("/:resume_id", append(_deleteresumeMw(), resume.DeleteResume)...)
			_resume.GET("/:resume_id", append(_getresumeMw(), resume.GetResume)...)
			_resume.PUT("/:resume_id", append(_updateresumeMw(), resume.UpdateResume)...)
			_resume.POST("/set-default", append(_setdefaultresumeMw(), resume.SetDefaultResume)...)
			_resume.POST("/upload", append(_uploadresumeMw(), resume.UploadResume)...)
		}
		{
			_user := _api.Group("/user", _userMw()...)
			_user.POST("/login", append(_loginMw(), interview.Login)...)
			_user.GET("/profile", append(_getprofileMw(), interview.GetProfile)...)
			_user.PUT("/profile", append(_updateprofileMw(), interview.UpdateProfile)...)
			_user.POST("/register", append(_registerMw(), interview.Register)...)
			{
				_create := _user.Group("/create", _createMw()...)
				_create.POST("/model", append(_createusermodelMw(), interview.CreateUserModel)...)
			}
			{
				_model := _user.Group("/model", _modelMw()...)
				_model.GET("/check", append(_checkusermodelconfiguredMw(), interview.CheckUserModelConfigured)...)
				_model.GET("/list", append(_listusermodelsMw(), interview.ListUserModels)...)
				{
					_delete := _model.Group("/delete", _deleteMw()...)
					_delete.DELETE("/:id", append(_deleteusermodelMw(), interview.DeleteUserModel)...)
				}
				{
					_details := _model.Group("/details", _detailsMw()...)
					_details.GET("/:id", append(_getusermodelMw(), interview.GetUserModel)...)
				}
				{
					_update := _model.Group("/update", _updateMw()...)
					_update.PUT("/:id", append(_updateusermodelMw(), interview.UpdateUserModel)...)
				}
				_model.POST("/switch", append(_switchusermodelMw(), interview.SwitchUserModel)...)
			}
			{
				_password := _user.Group("/password", _passwordMw()...)
				_password.POST("/forgot", append(_forgotpasswordMw(), interview.ForgotPassword)...)
				_password.POST("/reset", append(_resetpasswordMw(), interview.ResetPassword)...)
			}
			{
				_wechat := _user.Group("/wechat", _wechatMw()...)
				_wechat.GET("/callback", append(_wechatcallbackMw(), interview.WechatCallback)...)
				_wechat.GET("/login", append(_wechatloginMw(), interview.WechatLogin)...)
			}
			{
				_github := _user.Group("/github", _githubMw()...)
				_github.GET("/login", append(_githubloginMw(), interview.GitHubLogin)...)
				_github.POST("/callback", append(_githubcallbackMw(), interview.GitHubCallback)...)
			}
			{
				_google := _user.Group("/google", _googleMw()...)
				_google.GET("/login", append(_googleloginMw(), interview.GoogleLogin)...)
				_google.POST("/callback", append(_googlecallbackMw(), interview.GoogleCallback)...)
			}
		}
	}
}
