// Code generated by hertz generator.

package interview

import (
	serviceMiddleware "interview-agents/internal/middleware"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

var jwtPublicRoutes = map[string]struct{}{
	"/health":                   {},
	"/metrics":                  {},
	"/api/user/login":           {},
	"/api/user/register":        {},
	"/api/user/logout":          {},
	"/api/user/wechat/login":    {},
	"/api/user/wechat/callback": {},
	"/api/user/github/login":    {},
	"/api/user/github/callback": {},
	"/api/user/google/login":    {},
	"/api/user/google/callback": {},
	"/api/demo/create/model":    {},
	"/api/user/password/forgot": {},
	"/api/user/password/reset":  {},
	//"/api/interview/stream/start": {},
	// 支付 webhook 回调（无需 JWT）
	"/api/payment/webhook/stripe": {},
	"/api/payment/webhook/paypal": {},
}

func AuthSkipper() serviceMiddleware.JWTSkipper {
	return func(ctx *app.RequestContext) bool {
		if string(ctx.Method()) == consts.MethodOptions {
			return true
		}

		path := strings.TrimSuffix(string(ctx.Path()), "/")
		if _, ok := jwtPublicRoutes[path]; ok {
			return true
		}

		// 临时让admin接口也跳过认证，方便创建测试数据
		if strings.HasPrefix(path, "/api/admin/") {
			// 在上下文中设置一个默认的测试用户（admin 角色）
			ctx.Set("user_id", uint(1))
			ctx.Set("role", "admin")
			ctx.Set("username", "admin")
			return true
		}

		return false
	}
}

func rootMw() []app.HandlerFunc {
	return nil
}

func _apiMw() []app.HandlerFunc {
	return nil
}

func _userMw() []app.HandlerFunc {
	return nil
}

func _createMw() []app.HandlerFunc {
	return nil
}

func _createusermodelMw() []app.HandlerFunc {
	return nil
}

func _createusermodelsMw() []app.HandlerFunc {
	return nil
}

func _modelMw() []app.HandlerFunc {
	return nil
}

func _listusermodelsMw() []app.HandlerFunc {
	return nil
}

func _deleteMw() []app.HandlerFunc {
	return nil
}

func _deleteusermodelMw() []app.HandlerFunc {
	return nil
}

func _detailsMw() []app.HandlerFunc {
	return nil
}

func _getusermodelMw() []app.HandlerFunc {
	return nil
}

func _updateMw() []app.HandlerFunc {
	return nil
}

func _updateusermodelMw() []app.HandlerFunc {
	return nil
}

func _loginMw() []app.HandlerFunc {
	return nil
}

func _getprofileMw() []app.HandlerFunc {
	return nil
}

func _updateprofileMw() []app.HandlerFunc {
	return nil
}

func _registerMw() []app.HandlerFunc {
	return nil
}

func _logoutMw() []app.HandlerFunc {
	return nil
}

func _wechatMw() []app.HandlerFunc {
	return nil
}

func _wechatcallbackMw() []app.HandlerFunc {
	return nil
}

func _wechatloginMw() []app.HandlerFunc {
	return nil
}

func _githubMw() []app.HandlerFunc {
	return nil
}

func _githubloginMw() []app.HandlerFunc {
	return nil
}

func _githubcallbackMw() []app.HandlerFunc {
	return nil
}

func _googleMw() []app.HandlerFunc {
	return nil
}

func _googleloginMw() []app.HandlerFunc {
	return nil
}

func _googlecallbackMw() []app.HandlerFunc {
	return nil
}

func _passwordMw() []app.HandlerFunc {
	return nil
}

func _forgotpasswordMw() []app.HandlerFunc {
	return nil
}

func _resetpasswordMw() []app.HandlerFunc {
	return nil
}

func _interviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _continueinterviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _startMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _startinterviewstreamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listinterviewrecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinterviewrecordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _titlebankMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createusertitleinteractMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createinterviewlabelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createinterviewparseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createinterviewtitleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _create0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitinterviewanswerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinterviewevaluationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinterviewrecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getanswerrecordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdefaultresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserresumesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setdefaultresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkusermodelconfiguredMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _demoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdemomodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mianshiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _answerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitmianshianswerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interview0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _endmianshiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sessionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsessionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _streamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _startmianshistreamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmianshianswerrecordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmianshievaluationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmianshirecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _predictionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpredictiondetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpredictionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _predictMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _switchusermodelMw() []app.HandlerFunc {
	return nil
}
