// Code generated by hertz generator.

package interview

import (
	"context"
	"interview-agents/internal/agents/usecase/evaluation"
	"interview-agents/internal/model"
	"io"
	"log"
	"time"

	mianshiapi "interview-agents/api/model/interview"
	interviewsapi "interview-agents/api/model/resume"
	"interview-agents/api/response"
	"interview-agents/internal/middleware"
	core "interview-agents/internal/service/interview/engine"
	interviewservice "interview-agents/internal/service/resume"

	"github.com/cloudwego/hertz/pkg/app"
)

// StartInterviewStream 启动面试流程（SSE 模式）
// @router /api/interview/stream/start [POST]
func StartInterviewStream(ctx context.Context, c *app.RequestContext) {
	var req mianshiapi.InterviewStartInterviewRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}
	// 创建面试记录
	interviewSvc := interviewservice.NewInterviewService()
	recordDTO := &interviewsapi.InterviewRecordDTO{
		UserID:       int32(userID),
		Type:         req.Type,
		Difficulty:   req.Difficulty,
		Domain:       req.Domain,
		PositionName: req.PositionName,
		CompanyName:  req.CompanyName,
		Status:       "in_progress",
	}
	recordID, err := interviewSvc.CreateInterviewRecord(ctx, recordDTO)
	if err != nil {
		response.ErrorFromErr(ctx, c, err)
		return
	}
	// 处理简历参数
	var hasResume bool
	var resumeID int64
	if req.ResumeID != nil && *req.ResumeID > 0 {
		hasResume = true
		resumeID = *req.ResumeID
	}
	// 获取全局会话管理器并创建会话
	sm := core.GetGlobalSessionManager()
	var companyName, positionName string
	if req.CompanyName != nil {
		companyName = *req.CompanyName
	}
	if req.PositionName != nil {
		positionName = *req.PositionName
	}
	session := sm.CreateSessionWithDetails(userID, recordID, resumeID, hasResume, "", req.Type, req.Domain, req.Difficulty, companyName, positionName)

	// 创建可取消的 context
	cancelCtx, cancelFunc := context.WithCancel(ctx)
	session.CancelFunc = cancelFunc

	// 设置 SSE 响应头（必须在发送任何响应之前）
	core.SetupSSEResponse(c)

	// 建立 SSE 连接
	pipeReader, pipeWriter := io.Pipe()
	c.SetBodyStream(pipeReader, -1)

	// 启动异步面试循环（处理整个 SSE 流程）
	go func() {
		defer func(pipeWriter *io.PipeWriter) {
			err = pipeWriter.Close()
			if err != nil {

			}
		}(pipeWriter)
		// 发送会话ID事件（作为初始响应）
		startTime := session.StartTime.UnixMilli()
		err = core.SendSSEEvent(pipeWriter, map[string]interface{}{
			"type":       "session_id",
			"session_id": session.SessionID,
			"record_id":  recordID,
			"message":    "Interview started successfully",
			"start_time": startTime,
		})
		if err != nil {
			return
		}
		// 发送开始事件
		err = core.SendSSEEvent(pipeWriter, map[string]interface{}{
			"type":       "start",
			"message":    "面试已开始，正在生成第一个问题...",
			"session_id": session.SessionID,
		})
		if err != nil {
			return
		}
		// 创建面试引擎并运行
		engine := core.NewInterviewEngine(sm, interviewSvc, pipeWriter)
		//engine.RunInterviewLoop(cancelCtx, session)
		engine.RunInterviewLoopWithGraph(cancelCtx, session)
	}()
}

// SubmitInterviewAnswer 提交面试答案
// @router /api/interview/answer/submit [POST]
func SubmitInterviewAnswer(ctx context.Context, c *app.RequestContext) {
	var req mianshiapi.InterviewSubmitInterviewAnswerRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}
	if req.SessionID == "" {
		response.BadRequest(ctx, c, "session_id is required")
		return
	}
	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}
	// 获取全局会话管理器
	sm := core.GetGlobalSessionManager()
	session := sm.GetSession(req.SessionID)
	if session == nil {
		response.NotFound(ctx, c, "Session not found")
		return
	}
	if session.UserID != userID {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}
	answerToSubmit := req.Answer
	if req.Action != nil && (*req.Action == "quit" || *req.Action == "continue") {
		answerToSubmit = *req.Action
	}
	if err := sm.SubmitAnswer(req.SessionID, answerToSubmit); err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}
	// 计算问题索引和是否为最后一个问题
	questionIndex := session.QuestionCount
	isLastQuestion := false // 这个值由引擎在完成时设置

	resp := &mianshiapi.InterviewSubmitInterviewAnswerResponse{
		Status:         "received",
		Message:        &req.Answer,
		SessionID:      &req.SessionID,
		QuestionIndex:  &questionIndex,
		IsLastQuestion: &isLastQuestion,
	}

	response.Success(ctx, c, resp)
}

// GetSession 获取会话信息
// @router /api/interview/session/info [GET]
func GetSession(ctx context.Context, c *app.RequestContext) {
	var req mianshiapi.InterviewGetSessionRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	sm := core.GetGlobalSessionManager()
	session := sm.GetSession(req.SessionID)
	if session == nil {
		response.NotFound(ctx, c, "Session not found")
		return
	}

	if session.UserID != userID {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	// 构建返回的会话信息
	interviewSession := &mianshiapi.InterviewSession{
		SessionID:  session.SessionID,
		UserID:     int32(session.UserID),
		RecordID:   int64(session.RecordID),
		Type:       session.Type,
		Domain:     session.Domain,
		Difficulty: session.Difficulty,
		ResumeID:   &session.ResumeId,
		HasResume:  &session.HasResume,
		StartTime:  session.StartTime.UnixMilli(),
		Status:     session.Status,
	}

	if session.StartTime != (time.Time{}) {
		endTime := session.LastActivity.UnixMilli()
		interviewSession.EndTime = &endTime
	}

	elapsedTime := int64(time.Since(session.StartTime).Seconds())
	currentQuestionIndex := session.QuestionCount
	answeredCount := session.QuestionCount
	totalCount := session.QuestionCount

	resp := &mianshiapi.InterviewGetSessionResponse{
		Session:              interviewSession,
		CurrentQuestionIndex: &currentQuestionIndex,
		AnsweredCount:        &answeredCount,
		TotalCount:           &totalCount,
		ElapsedTime:          &elapsedTime,
	}

	response.Success(ctx, c, resp)
}

// EndInterview 结束面试
// @router /api/interview/interview/end [POST]
func EndInterview(ctx context.Context, c *app.RequestContext) {
	var req mianshiapi.InterviewEndInterviewRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	sm := core.GetGlobalSessionManager()
	session := sm.GetSession(req.SessionID)
	if session == nil {
		response.NotFound(ctx, c, "Session not found")
		return
	}

	if session.UserID != userID {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	// 更新会话状态
	session.Status = "completed"
	endTime := time.Now()
	session.LastActivity = endTime
	// 计算面试时长
	duration := int64(endTime.Sub(session.StartTime).Seconds())
	endTimeMs := endTime.UnixMilli()
	totalQuestions := session.QuestionCount
	answeredQuestions := session.QuestionCount // 已回答的问题数 = 主问题数

	// 取消面试循环，立即关闭 SSE 连接
	if session.CancelFunc != nil {
		session.CancelFunc()
	}
	interviewSvc := interviewservice.NewInterviewService()
	updateDTO := &interviewsapi.InterviewRecordDTO{
		ID:       int64(session.RecordID),
		UserID:   int32(session.UserID),
		Status:   "completed",
		Duration: &duration,
	}
	if err := interviewSvc.UpdateInterviewRecord(ctx, updateDTO); err != nil {
		response.ErrorFromErr(ctx, c, err)
		return
	}
	// 延迟删除会话
	go func() {
		time.Sleep(1 * time.Second)
		sm.DeleteSession(req.SessionID)
	}()
	log.Printf("[EndInterview] Interview ended, sessionID: %s, userID: %d, duration: %d seconds", req.SessionID, userID, duration)
	msg := "Interview ended successfully"
	resp := &mianshiapi.InterviewEndInterviewResponse{
		Status:            "success",
		Message:           &msg,
		Duration:          &duration,
		EndTime:           &endTimeMs,
		TotalQuestions:    &totalQuestions,
		AnsweredQuestions: &answeredQuestions,
	}
	response.Success(ctx, c, resp)
}

// GetInterviewEvaluation .
// @router /api/interview/evaluation [GET]
func GetInterviewEvaluation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mianshiapi.GetInterviewEvaluationRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}
	userId := middleware.GetUserID(c)
	if userId == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	reportID := uint64(req.ReportID)
	interviewService := interviewservice.NewInterviewService()
	//获取面试评估报告
	existingEvaluation, err := interviewService.GetInterviewEvaluation(ctx, userId, reportID)
	if err == nil && existingEvaluation != nil {
		response.Success(ctx, c, existingEvaluation)
		return
	}
	//如果没获取到面试评估报告则进行评估
	resp, err := evaluation.GenerateRecordEvaluation(ctx, userId, reportID)
	if err != nil {
		response.ErrorFromErr(ctx, c, err)
		return
	}

	// 检查 resp 是否为 nil（
	if resp == nil {
		response.InternalServerError(ctx, c, "Evaluation response is nil")
		return
	}

	response.Success(ctx, c, resp)
}

// GetInterviewAnswerRecord .
// @router /api/interview/answer-record [GET]
func GetInterviewAnswerRecord(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mianshiapi.GetInterviewAnswerRecordRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}
	userId := middleware.GetUserID(c)
	if userId == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	reportID := uint64(req.ReportID)
	interviewService := interviewservice.NewInterviewService()
	res, err := interviewService.GetAnswerReport(ctx, userId, reportID)

	// 如果数据库中已有数据且 records 不为空，直接返回
	if err == nil && res != nil {
		resMap, ok := res.(map[string]interface{})
		if ok {
			// 检查 records 字段是否存在且不为空
			if recordsData, exists := resMap["records"]; exists {
				// 尝试多种类型的断言
				switch v := recordsData.(type) {
				case []*model.AnswerRecordItem:
					if len(v) > 0 {
						response.Success(ctx, c, res)
						return
					}
				case []interface{}:
					if len(v) > 0 {
						response.Success(ctx, c, res)
						return
					}
				}
			}
		}
	}
	//如果数据库中获取失败则调用智能体生成评估
	reportId := req.ReportID
	resp, err := evaluation.GenerateAnswerRecordEvaluation(ctx, userId, uint64(reportId))
	if err != nil {
		response.ErrorFromErr(ctx, c, err)
		return
	}
	response.Success(ctx, c, resp)
}
