// Code generated by hertz generator.

package interview

import (
	"context"
	"errors"

	user "interview-agents/api/model/user"
	"interview-agents/api/response"
	"interview-agents/internal/middleware"
	userservice "interview-agents/internal/service/user"

	"github.com/cloudwego/hertz/pkg/app"
	"gorm.io/gorm"
)

// CreateUserModel .
// @router /api/user/create/model [POST]
func CreateUserModel(ctx context.Context, c *app.RequestContext) {
	var req user.CreateUserModelRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	state, err := userservice.NewModelManager().CreateUserModel(ctx, int64(userID), req)
	if err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	resp := user.NewCreateUserModelResponse()
	resp.State = state
	response.Success(ctx, c, resp)
}

// ForgotPassword .
// @router /api/user/password/forgot [POST]
func ForgotPassword(ctx context.Context, c *app.RequestContext) {
	var req user.ForgotPasswordRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	manager := userservice.NewUserManager()
	if err := manager.ForgotPassword(ctx, req.Email); err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	response.SuccessWithMessage(ctx, c, "重置邮件已发送，请检查您的邮箱", nil)
}

// ResetPassword .
// @router /api/user/password/reset [POST]
func ResetPassword(ctx context.Context, c *app.RequestContext) {
	var req user.ResetPasswordRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	manager := userservice.NewUserManager()
	if err := manager.ResetPassword(ctx, req.Token, req.Password); err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	response.SuccessWithMessage(ctx, c, "密码重置成功，请重新登录", nil)
}

// ListUserModels .
// @router /api/user/model/list [GET]
func ListUserModels(ctx context.Context, c *app.RequestContext) {
	var req user.ListUserModelsRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	page := req.GetPage()
	if page <= 0 {
		page = 1
	}
	size := req.GetSize()
	if size <= 0 {
		size = 10
	}
	if size > 100 {
		size = 100
	}

	models, total, err := userservice.NewModelManager().ListUserModels(ctx, int64(userID), req)
	if err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	resp := user.NewListUserModelsResponse()
	resp.List = make([]*user.UserModelItem, 0, len(models))
	for _, m := range models {
		resp.List = append(resp.List, userservice.ToUserModelItem(m))
	}
	resp.Total = total
	resp.Page = page
	resp.Size = size

	response.Success(ctx, c, resp)
}

// GetUserModel .
// @router /api/user/model/details/:id [GET]
func GetUserModel(ctx context.Context, c *app.RequestContext) {
	var req user.IDRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	record, err := userservice.NewModelManager().UserModelDetail(ctx, int64(userID), req.GetID())
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			response.NotFound(ctx, c, "User model not found")
			return
		}
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	resp := user.NewGetUserModelResponse()
	resp.Data = userservice.ToUserModelDetail(record)

	response.Success(ctx, c, resp)
}

// UpdateUserModel .
// @router /api/user/model/update/:id [PUT]
func UpdateUserModel(ctx context.Context, c *app.RequestContext) {
	var req user.UpdateUserModelRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	if err := userservice.NewModelManager().UpdateUserModel(ctx, int64(userID), req); err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			response.NotFound(ctx, c, "User model not found")
			return
		}
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	resp := user.NewUpdateUserModelResponse()
	response.Success(ctx, c, resp)
}

// DeleteUserModel .
// @router /api/user/model/delete/:id [DELETE]
func DeleteUserModel(ctx context.Context, c *app.RequestContext) {
	var req user.IDRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	if err := userservice.NewModelManager().DeleteUserModel(ctx, int64(userID), req.GetID()); err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			response.NotFound(ctx, c, "User model not found")
			return
		}
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	resp := user.NewDeleteUserModelResponse()
	response.Success(ctx, c, resp)
}

// Register .
// @router /api/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	manager := userservice.NewUserManager()
	registerResp, err := manager.Register(ctx, req)
	if err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	// 将 LoginResponse 包装在响应中
	data := map[string]interface{}{
		"token": registerResp.GetToken(),
		"user":  registerResp.GetUser(),
	}
	response.Success(ctx, c, data)
}

// Login .
// @router /api/user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	manager := userservice.NewUserManager()
	loginResp, err := manager.Login(ctx, req)
	if err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	// 将 LoginResponse 包装在响应中
	data := map[string]interface{}{
		"token": loginResp.GetToken(),
		"user":  loginResp.GetUser(),
	}
	response.Success(ctx, c, data)
}

// GetProfile .
// @router /api/user/profile [GET]
func GetProfile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.EmptyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	manager := userservice.NewUserManager()
	profile, err := manager.GetProfile(ctx, uint(userID))
	if err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	resp := new(user.GetProfileResponse)
	resp.Data = profile

	response.Success(ctx, c, resp)
}

// UpdateProfile .
// @router /api/user/profile [PUT]
func UpdateProfile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UpdateProfileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	manager := userservice.NewUserManager()
	profile, err := manager.UpdateProfile(ctx, userID, req)
	if err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	resp := new(user.UpdateProfileResponse)
	resp.Data = profile

	response.Success(ctx, c, resp)
}

// Logout .
// @router /api/user/logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	userID := middleware.GetUserID(c)
	data := map[string]interface{}{
		"status": "logged_out",
	}
	if userID != 0 {
		data["user_id"] = userID
	}
	response.Success(ctx, c, data)
}

// WechatLogin .
// @router /api/user/wechat/login [GET]
func WechatLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.EmptyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	manager := userservice.NewUserManager()
	resp, err := manager.WechatLogin(ctx)
	if err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	response.Success(ctx, c, resp)
}

// WechatCallback .
// @router /api/user/wechat/callback [GET]
func WechatCallback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.WechatCallbackRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	manager := userservice.NewUserManager()
	wechatResp, err := manager.WechatCallback(ctx, req)
	if err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	// 将 LoginResponse 包装在响应中
	data := map[string]interface{}{
		"token": wechatResp.GetToken(),
		"user":  wechatResp.GetUser(),
	}
	response.Success(ctx, c, data)
}

// GitHubLogin 返回 GitHub 授权跳转 URL，前端可重定向到该 URL
// @router /api/user/github/login [GET]
func GitHubLogin(ctx context.Context, c *app.RequestContext) {
	var req user.EmptyRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	manager := userservice.NewUserManager()
	resp, err := manager.GitHubLogin(ctx)
	if err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	response.Success(ctx, c, resp)
}

// GitHubCallback 用前端回调拿到的 code 换取 token 与用户信息（前端 POST code）
// @router /api/user/github/callback [POST]
func GitHubCallback(ctx context.Context, c *app.RequestContext) {
	var body struct {
		Code string `json:"code"`
	}
	if err := c.BindJSON(&body); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	manager := userservice.NewUserManager()
	loginResp, err := manager.GitHubCallback(ctx, body.Code)
	if err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	data := map[string]interface{}{
		"token": loginResp.GetToken(),
		"user":  loginResp.GetUser(),
	}
	response.Success(ctx, c, data)
}

// CheckUserModelConfigured .
// @router /api/user/model/check [GET]
func CheckUserModelConfigured(ctx context.Context, c *app.RequestContext) {
	var req user.EmptyRequest
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	modelManager := userservice.NewModelManager()
	defaultModel, err := modelManager.CheckUserModelConfigured(ctx, int64(userID))
	if err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	// 返回检查结果
	resp := user.NewCheckUserModelConfiguredResponse()

	// 判断是否已配置并启用：模型存在且 is_default = 1
	if defaultModel != nil && defaultModel.IsDefault == 1 {
		// 已配置并启用，可以开始问答
		resp.Configured = true
	} else {
		// 未配置或未启用，不能开始问答
		resp.Configured = false
	}

	response.Success(ctx, c, resp)
}

// SwitchUserModel .
// @router /api/user/model/switch [POST]
func SwitchUserModel(ctx context.Context, c *app.RequestContext) {
	// 简单的内部结构用于接收请求，也可以放到 IDL 里，为快这里直接定义
	type SwitchModelReq struct {
		OldModelID int64 `json:"old_model_id"`
		NewModelID int64 `json:"new_model_id" vd:"$>0"` // 新模型 ID 必填
	}

	var req SwitchModelReq
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(ctx, c, "Invalid request: "+err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	modelManager := userservice.NewModelManager()
	if err := modelManager.SwitchUserModel(ctx, int64(userID), req.OldModelID, req.NewModelID); err != nil {
		response.InternalServerError(ctx, c, err.Error())
		return
	}

	response.SuccessWithMessage(ctx, c, "模型切换成功", nil)
}
