// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package api

import (
	"github.com/apache/thrift/lib/go/thrift"
	"interview-agents/api/model/interview"
	"interview-agents/api/model/prediction"
	"interview-agents/api/model/resume"
	"interview-agents/api/model/user"
)

type UserService interface {
	user.UserService
}

type UserServiceClient struct {
	*user.UserServiceClient
}

func NewUserServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: user.NewUserServiceClientFactory(t, f),
	}
}

func NewUserServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: user.NewUserServiceClientProtocol(t, iprot, oprot),
	}
}

func NewUserServiceClient(c thrift.TClient) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: user.NewUserServiceClient(c),
	}
}

type ResumeService interface {
	resume.ResumeService
}

type ResumeServiceClient struct {
	*resume.ResumeServiceClient
}

func NewResumeServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ResumeServiceClient {
	return &ResumeServiceClient{
		ResumeServiceClient: resume.NewResumeServiceClientFactory(t, f),
	}
}

func NewResumeServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ResumeServiceClient {
	return &ResumeServiceClient{
		ResumeServiceClient: resume.NewResumeServiceClientProtocol(t, iprot, oprot),
	}
}

func NewResumeServiceClient(c thrift.TClient) *ResumeServiceClient {
	return &ResumeServiceClient{
		ResumeServiceClient: resume.NewResumeServiceClient(c),
	}
}

type InterviewService interface {
	interview.InterviewService
}

type InterviewServiceClient struct {
	*interview.InterviewServiceClient
}

func NewInterviewServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *InterviewServiceClient {
	return &InterviewServiceClient{
		InterviewServiceClient: interview.NewInterviewServiceClientFactory(t, f),
	}
}

func NewInterviewServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *InterviewServiceClient {
	return &InterviewServiceClient{
		InterviewServiceClient: interview.NewInterviewServiceClientProtocol(t, iprot, oprot),
	}
}

func NewInterviewServiceClient(c thrift.TClient) *InterviewServiceClient {
	return &InterviewServiceClient{
		InterviewServiceClient: interview.NewInterviewServiceClient(c),
	}
}

type PredictionService interface {
	prediction.PredictionService
}

type PredictionServiceClient struct {
	*prediction.PredictionServiceClient
}

func NewPredictionServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *PredictionServiceClient {
	return &PredictionServiceClient{
		PredictionServiceClient: prediction.NewPredictionServiceClientFactory(t, f),
	}
}

func NewPredictionServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *PredictionServiceClient {
	return &PredictionServiceClient{
		PredictionServiceClient: prediction.NewPredictionServiceClientProtocol(t, iprot, oprot),
	}
}

func NewPredictionServiceClient(c thrift.TClient) *PredictionServiceClient {
	return &PredictionServiceClient{
		PredictionServiceClient: prediction.NewPredictionServiceClient(c),
	}
}

type UserServiceProcessor struct {
	*user.UserServiceProcessor
}

func NewUserServiceProcessor(handler UserService) *UserServiceProcessor {
	self := &UserServiceProcessor{user.NewUserServiceProcessor(handler)}
	return self
}

type ResumeServiceProcessor struct {
	*resume.ResumeServiceProcessor
}

func NewResumeServiceProcessor(handler ResumeService) *ResumeServiceProcessor {
	self := &ResumeServiceProcessor{resume.NewResumeServiceProcessor(handler)}
	return self
}

type InterviewServiceProcessor struct {
	*interview.InterviewServiceProcessor
}

func NewInterviewServiceProcessor(handler InterviewService) *InterviewServiceProcessor {
	self := &InterviewServiceProcessor{interview.NewInterviewServiceProcessor(handler)}
	return self
}

type PredictionServiceProcessor struct {
	*prediction.PredictionServiceProcessor
}

func NewPredictionServiceProcessor(handler PredictionService) *PredictionServiceProcessor {
	self := &PredictionServiceProcessor{prediction.NewPredictionServiceProcessor(handler)}
	return self
}
